name: ruff
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check-ruff-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
        cache: 'pip'
        cache-dependency-path: '.github/workflows/ruff.yml'
    - run: pip install ruff==0.11.8
    - run: ruff format --diff .
